frontend:
  replicaCount: 2
  image:
    repository: veeradockerhub/lifedrop-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    targetPort: 80

backend:
  replicaCount: 2
  image:
    repository: veeradockerhub/lifedrop-backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  env:
    PORT: "5000"
    NODE_ENV: "production"
    MONGO_URI: "mongodb://mongo:27017/lifedrop"

mongodb:
  image:
    repository: mongo
    tag: "7"
    pullPolicy: IfNotPresent
  service:
    port: 27017
  persistence:
    size: 5Gi
    storageClass: gp3

nginx:
  replicaCount: 2
  image:
    repository: nginx
    tag: "1.25-alpine"
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80
