apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: lifedrop-frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
