apiVersion: v1
kind: Service
metadata:
  name: lifedrop-nginx
spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    app: lifedrop-nginx
  ports:
    - name: http
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
      protocol: TCP
